version: '3.8'

services:
  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - my_network

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:8080"
    networks:
      - my_network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - my_network
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

networks:
  my_network:
    driver: bridge
