version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - ./frontend/dist:/app/static

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    environment:
      - VUE_APP_BACKEND_URL=http://backend:5000
